Repository Yamato-Security/hayabusa-rules, pull requests merged in 2022-03, with the labels that each got.

#17 Rules to detect bad Windows drivers
  config/eventkey_alias.txt
  config/exclude_rules.txt
  hayabusa/non-default/alerts/Security/5038-6281-6410_CodeIntegrityProblem-PossibleModification.yml
  hayabusa/sysmon/alerts/6_CodeSigning_DriverLoadedWithInvalidSignature.yml
  hayabusa/sysmon/alerts/6_CodeSigning_UnsignedDriverLoaded.yml
Labels: rule update, high priority

#18 create TOC #12
  README-Japanese.md
  README.md
Labels: documentation

#23 fixed test_files rule id #22
  config/exclude_rules.txt
  tools/sigmac/test_files/expected_rules/test_rules/test0001.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0002.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0003.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0004.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0005.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0006.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0007.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0008.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0009.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0010.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0011.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0012.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0013.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0014.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0015.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0016.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0017.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0018.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0019.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0020.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0021.yml
  tools/sigmac/test_files/expected_rules/test_rules/test0022.yml
  tools/sigmac/test_files/test_rules/test0001.yml
  tools/sigmac/test_files/test_rules/test0002.yml
  tools/sigmac/test_files/test_rules/test0003.yml
  tools/sigmac/test_files/test_rules/test0004.yml
  tools/sigmac/test_files/test_rules/test0005.yml
  tools/sigmac/test_files/test_rules/test0006.yml
  tools/sigmac/test_files/test_rules/test0007.yml
  tools/sigmac/test_files/test_rules/test0008.yml
  tools/sigmac/test_files/test_rules/test0009.yml
  tools/sigmac/test_files/test_rules/test0010.yml
  tools/sigmac/test_files/test_rules/test0011.yml
  tools/sigmac/test_files/test_rules/test0012.yml
  tools/sigmac/test_files/test_rules/test0013.yml
  tools/sigmac/test_files/test_rules/test0014.yml
  tools/sigmac/test_files/test_rules/test0015.yml
  tools/sigmac/test_files/test_rules/test0016.yml
  tools/sigmac/test_files/test_rules/test0017.yml
  tools/sigmac/test_files/test_rules/test0018.yml
  tools/sigmac/test_files/test_rules/test0019.yml
  tools/sigmac/test_files/test_rules/test0020.yml
  tools/sigmac/test_files/test_rules/test0021.yml
  tools/sigmac/test_files/test_rules/test0022.yml
Labels: bug

#34 Exclude githubworkflow yaml main#30
  .github/workflows/update-sigmarule.yaml
  README-Japanese.md
  README.md
Labels: documentation
