Repository Yamato-Security/hayabusa-rules, pull requests merged in 2022-12, with the labels that each got.

#229 fix readme japanese
  README-Japanese.md
Labels: bug

#232 update readme EventData change to Data
  README-Japanese.md
  README.md
Labels: enhancement

#234 stop regex conversion
  tools/sigmac/hayabusa.py
Labels: bug, high priority

#243 fix: keep Sigma YAML `null` value as is
  tools/sigmac/hayabusa.py
Labels: bug

#254 added endswithfield in readme
  README-Japanese.md
  README.md
Labels: documentation
