Repository Yamato-Security/hayabusa-rules, pull requests merged in 2023-12, with the labels that each got.

#542 feat: add detail PowerShellClassic
  hayabusa/builtin/PowerShellClassic/PwShClassic_400_Info_PwShEngineStarted.yml
Labels: enhancement

#547 feat: add rule parse error check GitHub Actions
  .github/workflows/rule-parse-error-check.yaml
Labels: enhancement

#554 fix: add check for incompatible modifier
  sigma/builtin/placeholder/security/win_security_exploit_cve_2020_1472.yml
  sigma/builtin/placeholder/security/win_security_potential_pass_the_hash.yml
  sigma/builtin/placeholder/security/win_security_remote_registry_management_via_reg.yml
  sigma/builtin/placeholder/security/win_security_susp_interactive_logons.yml
  tools/sigmac/logsource_mapping.py
  tools/sigmac/test_logsource_mapping.py
Labels: bug

#553 add list of unsupported modifiers
  README-Japanese.md
  README.md
Labels: documentation

#557 fix broken pipe typo
  config/default_details.txt
  hayabusa/sysmon/Sysmon_13_RegKeyValueSet_RuleAlert.yml
Labels: bug
