Repository Yamato-Security/hayabusa-rules, pull requests merged in 2024-11, with the labels that each got.

#762 feat: add RDS Session Reconnect rule (EID:25)
  hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_25_Info_RDS-SessReconn.yml
Labels: enhancement

#763 chg: add `Microsoft-Windows-TerminalServices-Gateway/Operational` abbreviation
  README-Japanese.md
  README.md
  config/channel_abbreviations.txt
  config/provider_abbreviations.txt
Labels: enhancement

#765 udpate rds gtw rules
  config/eventkey_alias.txt
  hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_302_Info_LogonSuccess.yml
  hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_302_Low_LogonError.yml
  hayabusa/builtin/TerminalServices-Gateway_Op/RDS_Gateway_303_Info_Logoff.yml
Labels: enhancement

#769 update RDP rules
  hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_21_Info_RDP-Logon.yml
  hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_22_Info_RDP-SessStart_Noisy.yml
  hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_23_Info_RDP-Logoff.yml
  hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_24_Info_RDP-Disconnect.yml
  hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_25_Info_RDP-Reconnect.yml
  hayabusa/builtin/TerminalServices-RemoteConnectionManager_Op/RemoteConnManger_1149_Info_RDP-LogonAttempt.yml
  hayabusa/builtin/TerminalServices-RemoteConnectionManager_Op/RemoteConnManger_261_Info_RDP-Conn_Noisy.yml
  hayabusa/builtin/TerminalServices-RemoteConnectionManager_Op/RemoteConnManger_261_Info_RDS-Conn_Noisy.yml
Labels: enhancement

#771 make the levels consistent for correlation referenced rules
  hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_UserGuessing_Correlation.yml
  hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml
  hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4648_Med_ExplicitLogon_PW-Spray_Correlation.yml
Labels: bug

#778 readme-2.19.0
  README-Japanese.md
  README.md
  config/closing_messages.txt
  config/opening_messages.txt
  doc/SupportedSigmaFieldModifiers.md
  hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Med_Logon-Type9-NewInteractive_PossibleTokenImpersonation.yml
  hayabusa/sysmon/Sysmon_1_Low_ExeFileRenamed.yml
  hayabusa/sysmon/Sysmon_1_ProcExec_High_LOLBAS-Rename.yml
  scripts/supported_modifiers_check/README.md
  scripts/supported_modifiers_check/supported-modifier.py
Labels: documentation

#782 chg: add supported modifier (`contains|cased`, `startswith|cased`, `endswith|cased`)
  doc/SupportedSigmaFieldModifiers.md
  scripts/supported_modifiers_check/supported-modifier.py
Labels: enhancement
