Repository Yamato-Security/hayabusa-rules, pull requests merged in 2024-10, with the labels that each got.

#726 reduce config files update readme
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  config/regex/LOLBAS_commands.txt
  config/regex/LOLBAS_paths.txt
  config/regex/allowlist_legitimate_services.txt
  config/regex/detectlist_suspicous_services.txt
  config/regex/record_data_filter.txt
  config/statistics_event_info.txt
  hayabusa/builtin/System/Sys_7045_High_ServiceInstalled_PossiblyMaliciousSvcInstalled.yml
  hayabusa/builtin/System/Sys_7045_High_ServiceInstalled_SuspiciousServiceName.yml
  hayabusa/builtin/System/Sys_7045_High_ServiceInstalled_SuspiciousServicePath.yml
Labels: documentation, enhancement

#731 fix external file reference error
  CHANGELOG-Japanese.md
  CHANGELOG.md
  hayabusa/builtin/Security/DetailedTracking/ProcessCreation/Sec_4688_Low_ProcExec_PossibleLOLBIN-Abuse.yml
  hayabusa/sysmon/Sysmon_1_ProcExec_High_LOLBAS-Rename.yml
Labels: bug

#733 refactor: remove unused `event_id_info.txt`
  config/event_id_info.txt
Labels: enhancement

#743 fix: modify unsupported modifiers
  doc/SupportedSigmaFieldModifiers.md
  scripts/supported_modifiers_check/README.md
  scripts/supported_modifiers_check/supported-modifier.py
Labels: bug

#744 add windash config file
  config/windash_characters.txt
Labels: enhancement

#748 fix: Do not update `SupportedSigmaFieldModifiers.md` when there are no updates
  doc/SupportedSigmaFieldModifiers.md
  scripts/supported_modifiers_check/supported-modifier.py
Labels: bug

#740 add sigma correlation doc
  README-Japanese.md
  README.md
  config/exclude_rules.txt
  hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_UserGuessing_Cnt_Deprecated.yml
  hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_UserGuessing_Correlation.yml
  hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Cnt_Deprecated.yml
  hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4625_Med_LogonFail_WrongPW_PW-Guessing_Correlation.yml
Labels: documentation

#751 feat: Add correlation rules support tables to SupportedSigmaFieldModifiers.md
  doc/SupportedSigmaFieldModifiers.md
  scripts/supported_modifiers_check/supported-modifier.py
Labels: enhancement

#755 fix: changed GitHub Action's linux package name
  .github/workflows/rule-parse-error-check.yaml
  .github/workflows/update-sigmarule.yaml
Labels: bug
