Repository Yamato-Security/hayabusa-rules, pull requests merged in 2024-04, with the labels that each got.

#640 fix: update GitHub action's hayabusa zip name
  .github/workflows/rule-parse-error-check.yaml
Labels: bug

#641 fix: update hayabusa zip name
  .github/workflows/update-sigmarule.yaml
Labels: bug

#642 display rule parse error log in console when rule parse error
  .github/workflows/rule-parse-error-check.yaml
Labels: enhancement

#643 chg: display error log when rule parse error in Github Actions
  .github/workflows/rule-parse-error-check.yaml
Labels: enhancement

#645 chg: output error log when rule parse error
  .github/workflows/update-sigmarule.yaml
Labels: bug

#650 469-fix-UserDataUser-alias
  config/eventkey_alias.txt
  hayabusa/builtin/WMI-Activity_Op/WMI_5860_Info_TempEventConsumerRegistered.yml
Labels: bug

#651 add windash to readme
  README-Japanese.md
  README.md
Labels: documentation, enhancement

#657 fix: declare `Channel` explicitly
  hayabusa/builtin/PowerShell_Op/PwSh_4103_Info_PipelineExecution.yml
  hayabusa/builtin/PowerShell_Op/PwSh_4104_Info_ScriptblockLog.yml
  hayabusa/builtin/PowerShell_Op/PwSh_4104_Med_ScriptblockLog_PotentiallyMalicious.yml
Labels: bug
