Repository Yamato-Security/hayabusa-rules, pull requests merged in 2024-02, with the labels that each got.

#595 Add System 6009 rule
  hayabusa/builtin/System/Sys_6009_Info_ComputerStartup.yml
Labels: enhancement

#596 chg: update logsource categories
  tools/sigmac/poetry.lock
  tools/sigmac/pyproject.toml
  tools/sigmac/sysmon.yaml
  tools/sigmac/windows-antivirus.yaml
  tools/sigmac/windows-services.yaml
Labels: enhancement

#599 fix: add details key string
  hayabusa/builtin/UnkwnChannEID_Med_PossibleHiddenShellcode.yml
Labels: bug

#606 test: fix failing unittest
  tools/sigmac/logsource_mapping.py
  tools/sigmac/test_logsource_mapping.py
Labels: invalid
